defaultPortal: ayo_pd_demo_cfw
portals:
  - name: ayo_pd_demo_cfw
    portalId: 26305460
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          COjjlsG6MBIJAA0AAAAA4A0DGLTHxQwg5eGPFSju6QwyFA9zMfNX_d2W113Ul3n8oXpzxHH3OjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhRoucT8iEHMcyrMj7_pCT1nnQZmwUoDZXUxUgBaAA
        expiresAt: '2022-10-05T12:36:26.219Z'
    personalAccessKey: >-
      CiRldTEtZTQ0Ny03NmFjLTQ3MzUtOThhOS1kMGEyNWJmYjIxYzYQtMfFDBjl4Y8VKhkABeaRglAK_F0JGcwAf5Z0ecxahpDXusrwSgNldTE
