defaultPortal: ayo_pd_demo
portals:
  - name: ayo_pd_demo
    portalId: 26305460
    authType: personalaccesskey
    auth:
      tokenInfo:
        accessToken: >-
          CNi6k8C6MBIJAA0AAAAA4A0DGLTHxQwg5eGPFSju6QwyFGt8v-kyy-jr5TrU50oskI6ah00_OjcAAARBAAAAeAAAAAAAAAAAAAAAAAAAAAQAAMAHAP7_MTwAAAYAAABgAAAAAAAAAAAAAAAAADACQhQG8G0QFBDz2aWRoX7raLDiOdpvqEoDZXUxUgBaAA
        expiresAt: '2022-10-05T12:00:34.651Z'
    personalAccessKey: >-
      CiRldTEtZTQ0Ny03NmFjLTQ3MzUtOThhOS1kMGEyNWJmYjIxYzYQtMfFDBjl4Y8VKhkABeaRglAK_F0JGcwAf5Z0ecxahpDXusrwSgNldTE
